# Generated by Django 5.2 on 2025-05-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancesubcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancelead',
            name='product',
        ),
        migrations.DeleteModel(
            name='InsuranceProduct',
        ),
    ]
