# Generated by Django 5.2 on 2025-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancemaincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
