# Generated by Django 5.2 on 2025-05-19 16:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurancemaincategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category_images'),
        ),
    ]
