# Generated by Django 5.2 on 2025-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_insurancesubcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancemaincategory',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurancesubcategory',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
