# Generated by Django 5.2 on 2025-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurancemaincategory_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancemaincategory',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurancesubcategory',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
