# Generated by Django 5.2 on 2025-06-03 14:41

import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_category_tag_story_externallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category_images')),
                ('private', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
            },
        ),
        migrations.RemoveField(
            model_name='insurancesubcategory',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='insurancelead',
            name='name',
        ),
        migrations.AddField(
            model_name='insurancelead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancelead',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancelead',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category_images')),
                ('private', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='insurance.maincategory')),
            ],
        ),
        migrations.AddField(
            model_name='insurancelead',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='insurance.subcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InsuranceMainCategory',
        ),
        migrations.DeleteModel(
            name='InsuranceSubCategory',
        ),
    ]
