# Generated by Django 5.2 on 2025-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_maincategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_category',
            field=models.ManyToManyField(related_name='subcategories', to='insurance.maincategory'),
        ),
    ]
