# Generated by Django 5.2 on 2025-09-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_maincategory_seo_keywords_subcategory_seo_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Main Categories'},
        ),
    ]
