# Generated by Django 5.2 on 2025-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_alter_maincategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
