# Generated by Django 5.2 on 2025-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_alter_maincategory_image_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
