services:
  - type: web
    name: my-django-app
    env: python 3.12.3
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput

    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings